
version: "3"

services:
  db:
    image: postgres
  dj:
    container_name: dj
    build: django
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./django:/code
    ports:
      - "8000"
    depends_on:
      - db
